name: Go ✅

on: [push, pull_request, workflow_dispatch ]

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v3
        
      - name: Check ✅
        uses: cedrickring/golang-action@1.7.0
        continue-on-error: false
        
